#!/usr/bin/expect
# reboot-modem.exp
# @author: Nguyen Hong Hai
set USERNAME "root"
set PASSWORD "VBMkaeqwzvpi7HV"
set ROUTERIP "192.168.1.1"
# Your username@host
spawn ssh $USERNAME@$ROUTERIP -tt -o ConnectTimeout=2
expect "password: "
# Your SSH password goes here
send -- "$PASSWORD\r"
expect "#ONT>"
# Get into shell
send "system/shell\r"
expect "#ONT/system/shell>"
# Perform the reboot command
send "/sbin/reboot\r"
expect eof